title = "Andrew Hill | Web Developer"
baseURL = "http://dev.andrewhill.io"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Web Developer"
    author = "Andrew Hill"
    description = "Full-stack web developer based out of Louisville, KY"
    logoBig = "/images/andrewhill.png"
    logoSmall = "/images/ah.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/andrewhill.png"
    linkedin = "andrew-hill-7b328b81"
    github = "arhill05"
    email = "me@andrewhill.io"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
